const List<String> quotes = [
  '"Most everything I have done in my life, I have copied from someone else." - Sam Walton',
  '"The cowards never started, the weak died along the way. That leaves us." - Phil Knight',
  '"We are all self-made, but only the successful will truly admit it." - Earl Nightingale',
  '"I was an overnight success all right, but 30 years is a long, long night." - Ray Kroc',
  '"To be able, at any moment, to sacrifice who you are for what you will become." - Eric Thomas',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '20',
  '21',
  '22',
  '23',
  '24',
  '25',
  '26',
  '27',
  '28',
  '29',
  '30',
];
