const List<String> quotes = [
  '"Most everything I have done in my life, I have copied from someone else." - Sam Walton',
  '"The cowards never started, the weak died along the way. That leaves us." - Phil Knight',
  '"We are all self-made, but only the successful will truly admit it." - Earl Nightingale',
  '"I was an overnight success all right, but 30 years is a long, long night." - Ray Kroc',
  '"To be able, at any moment, to sacrifice who you are for what you will become." - Eric Thomas',
  'Make sure every day you do what matters most.',
  'Extraordinary results happen only when you give the best you have to become the best you can be.',
  '"People do not decide their futures, they decide their habits and their habits decide their futures." —F. M. Alexander',
  '"We are what we repeatedly do. Excellence, then, is not an act, but a habit." - Aristotle',
  'A different result requires doing something different.',
  'Success is about doing the right thing, not about doing everything right.',
  'Don’t let small thinking cut your life down to size. Think big, aim high, act bold. And see just how big you can blow up your life.',
  'The key to success is time. Success is built sequentially. It’s one thing at a time.',
  '"We are kept from our goal, not by obstacles but by a clear path to a lesser goal." —Robert Brault',
  'One of the most empowering moments of my life came when I realized that life is a question and how we live it is our answer.',
  'Anyone who dreams of an uncommon life eventually discovers there is no choice but to seek an uncommon approach to living it.',
  'Achievers always work from a clear sense of priority.',
  '"Focus is a matter of deciding what things you’re not going to do." —John Carmack',
  '"It’s not enough to be busy, so are the ants. The question is, what are we busy about?"',
  '"Extraordinary results are directly determined by how narrow you can make your focus.',
  'Knocking out a hundred tasks for whatever the reason is a poor substitute for doing even one task that’s meaningful.',
  '"It is those who concentrate on but one thing at a time who advance in this world." — Og Mandino',
  '"Things which matter most must never be at the mercy of things which matter least." —Johann Wolfgang von Goethe',
  'Be like a postage stamp–stick to one thing until you get there.',
  'Don\'t fear big. Fear mediocrity. Fear waste. Fear the lack of living to your fullest.',
  'Taking complete ownership of your outcomes by holding no one but yourself responsible for them is the most powerful thing you can do to drive your success.',
  'We are kept from our goal, not by obstacles but by a clear path to a lesser goal.',
  'Pursue something so important, that even if you fail, the world is better off for you having tried.',
  '"You start out as an unknown quantity, with just a dream and a commitment." - Sam Walton',
  '"Dwell on the beauty of life. Watch the stars, and see yourself running with them." ― Marcus Aurelius',
  '"The happiness of your life depends upon the quality of your thoughts." ― Marcus Aurelius',
  '"Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth." ― Marcus Aurelius',
  '"You have power over your mind - not outside events. Realize this, and you will find strength." ― Marcus Aurelius',
  '"Waste no more time arguing about what a good man should be. Be one." ― Marcus Aurelius',
  '"When you arise in the morning think of what a privilege it is to be alive, to think, to enjoy, to love ..." ― Marcus Aurelius',
  '"The soul becomes dyed with the colour of its thoughts." ― Marcus Aurelius',
  '"It is not death that a man should fear, but he should fear never beginning to live." ― Marcus Aurelius',
  '"Our life is what our thoughts make it." ― Marcus Aurelius',
  '"Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present." ― Marcus Aurelius',
  '"If it is not right do not do it; if it is not true do not say it." ― Marcus Aurelius',
  '"I have often wondered how it is that every man loves himself more than all the rest of men, but yet sets less value on his own opinion of himself than on the opinion of others." ― Marcus Aurelius',
  '"Very little is needed to make a happy life; it is all within yourself in your way of thinking." ― Marcus Aurelius',
  '"Do every act of your life as though it were the very last act of your life." ― Marcus Aurelius',
  '"What we do now echoes in eternity." ― Marcus Aurelius',
  '"The man who fears death will never do anything worthy of a man who is alive." ― Seneca',
  '"It is not what you endure that matters, but how you endure it." ― Seneca',
  '"Let us take pleasure in what we have received and make no comparison; no man will ever be happy if tortured by the greater happiness of another." ― Seneca',
  '"If you really want to escape the things that harass you, what you’re needing is not to be in a different place but to be a different person." ― Seneca',
  '"If you live in harmony with nature you will never be poor; if you live according what others think, you will never be rich." ― Seneca',
  '"It is not the man who has too little that is poor, but the one who hankers after more." ― Seneca',
  '"To be everywhere is to be nowhere." ― Seneca',
  '"The difficulty comes from our lack of confidence." ― Seneca',
  '"The beginning is the most important part of the work." ― Plato',
  '"For the things we have to learn before we can do them, we learn by doing them." ― Aristotle',
  'In the end, we are our choices.',
  'The person passionate about what he or she is doing will outwork and outlast the guy motivated solely by making money.',
  '"In my experience, each failure contains the seeds of your next success—if you are willing to learn from it." ― Paul Allen',
  'There\'s almost nothing you can\'t accomplish if you set your mind to it. - Ray Kroc',
  'Pick yourself up, do it all over again, only even better this time.',
  'Fall seven times, stand up eight.',
  '"If you’re not failing, you’re not pushing your limits, and if you’re not pushing your limits, you’re not maximizing your potential." - Ray Dalio',
  '"Maturity is the ability to reject good alternatives in order to pursue even better ones." - Ray Dalio',
  '"I just want to be right—I don’t care if the right answer comes from me." - Ray Dalio',
  '"It\'s more important to do big things well than to do the small things perfectly." - Ray Dalio',
  'Good ideas are always crazy until they’re not.',
  'The true measure of a man is how he treats someone who can do him absolutely no good. - Samuel Johnson',
  '”All our dreams can come true, if we have the courage to pursue them.” – Walt Disney',
  '“The secret of getting ahead is getting started.” – Mark Twain',
  '“It’s hard to beat a person who never gives up.” – Babe Ruth',
  '“If people are doubting how far you can go, go so far that you can’t hear them anymore.” – Michele Ruiz',
  'You can either experience the pain of discipline or the pain of regret. The choice is yours.',
  'Don’t be afraid to give up the good to go for the great.',
  'Some people want it to happen, some wish it would happen, others make it happen.',
  '“Great things are done by a series of small things brought together.” – Vincent Van Gogh',
  'The hard days are what make you stronger.',
  '“Work hard in silence, let your success be the noise.” – Frank Ocean',
  '“Opportunity is missed by most people because it is dressed in overalls and looks like work.” – Thomas Edison',
  '“The only difference between ordinary and extraordinary is that little extra.” – Jimmy Johnson',
  '“Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.” – Earl Nightingale',
  '“If you work on something a little bit every day, you end up with something that is massive.” – Kenneth Goldsmith',
  '“The big secret in life is that there is no secret. Whatever your goal, you can get there if you’re willing to work.” – Oprah Winfrey',
  '“If you cannot do great things, do small things in a great way.” – Napoleon Hill',
  'At any given moment you have the power to say: this is not how my story is going to end.',
  '“Amateus sit around and wait for inspiration. The rest of us just get up and go to work.” – Stephen King',
  '“Nothing will work unless you do.” – Maya Angelou',
  'Don’t limit your challenges. Challenge your limits.',
  'Whenever you find yourself doubting how far you can go, just remember how far you have come.',
  '“Dreams don’t work unless you do.” – John C. Maxwell',
  '“I hated every minute of training, but I said, ‘Don’t quit. Suffer now and live the rest of your life as a champion.” – Muhammad Ali',
  '“If you want to fly give up everything that weighs you down.” – Buddha',
  '“Doubt kills more dreams than failure ever will.” – Suzy Kassem',
  '“I never lose. Either I win or learn.” – Nelson Mandela',
  '“Today is your opportunity to build the tomorrow you want.” – Ken Poirot',
  '“Getting over a painful experience is much like crossing the monkey bars. You have to let go at some point in order to move forward.” – C.S. Lewis',
  '“Focus on being productive instead of busy.” – Tim Ferriss',
  '“You don’t need to see the whole staircase, just take the first step.” – Martin Luther King Jr.',
  '“The big lesson in life is never be scared of anyone or anything.” – Frank Sinatra',
  '“Be so good they can’t ignore you.” – Steve Martin',
  '“Do the best you can. No one can do more than that.” – John Wooden',
  '“Do what you can, with what you have, where you are.” – Theodore Roosevelt',
  '"It\'s never too late to be what you might’ve been." – George Eliot',
  'Don’t let what you can’t do interfere with what you can do.',
  '“Twenty years from now you’ll be more disappointed by the things you did not do than the ones you did.” – Mark Twain',
  '“I am thankful for all of those who said NO to me. It’s because of them I’m doing it myself.” – Wayne W. Dyer',
  '“You can’t go back and change the beginning, but you can start where you are and change the ending.” – C.S. Lewis',
];
